<definitions name="BMI_Calculator_Service" targetNamespace="http://www.example.com/wsdl/BMICalculatorService.wsdl" 
  xmlns="http://schemas.xmlsoap.org/wsdl/" 
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
  xmlns:tns="http://www.example.com/wsdl/BMICalculatorService.wsdl" 
  xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <message name="calcularIMCRequest">
    <part name="nombre" type="xsd:string"/>
    <part name="peso" type="xsd:float"/>
    <part name="altura" type="xsd:float"/>
  </message>

  <message name="calcularIMCResponse">
    <part name="mensaje" type="xsd:string"/>
  </message>

  <portType name="CalculadoraIMC_PortType">
    <operation name="calcularIMC">
      <input message="tns:calcularIMCRequest"/>
      <output message="tns:calcularIMCResponse"/>
    </operation>
  </portType>

  <binding name="CalculadoraIMC_Binding" type="tns:CalculadoraIMC_PortType">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="calcularIMC">
      <soap:operation soapAction="calcularIMC"/>
      <input>
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:example:bmicalculatorservice" use="encoded"/>
      </input>
      <output>
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:example:bmicalculatorservice" use="encoded"/>
      </output>
    </operation>
  </binding>

  <service name="CalculadoraIMC_Service">
    <documentation>WSDL File for BMICalculatorService</documentation>
    <port binding="tns:CalculadoraIMC_Binding" name="CalculadoraIMC_Port">
      <soap:address location="http://localhost:3031/bmiCalculator/" />
    </port>
  </service>
</definitions>
